# Generated by Django 5.2.9 on 2026-01-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='property_city', to='airbnb_app.city'),
            preserve_default=False,
        ),
    ]
